### ISSUE TITLE
output file, input file flag bug

### ISSUE THREAD

**Issue by renzobalb** [pacific-2020/pacific#4]
If a full path to -i and a path to the -o flag are given, then no output comes out.

See below:

```
python ../PACIFIC.py   -i ~/pacific/pacific/test/test.fa.gz   -m ../model/pacific.01.pacific_9mers_nonGPU.h5   -t ../model/tokenizer.01.pacific_9mers.pickle   -l ../model/label_maker.01.pacific_9mers.pickle  -c 200 -o /media/dstore/renzo/pacific/pacific/test
```

Error:
Writing final output FASTA /media/dstore/renzo/pacific/pacific/test/pacificoutput_test.fa.gz
Traceback (most recent call last):
  File "../PACIFIC.py", line 363, in <module>
    with open(OUTPUTDIR+'/'+f,'rb') as fd:
FileNotFoundError: [Errno 2] No such file or directory: '/media/dstore/renzo/pacific/pacific/test//media/dstore/renzo/pacific/pacific/test/tmp_output_test.fa.gz_200'

**Comment by hp2048** [comment]
Resolved in latest commit
