### ISSUE TITLE
output file writing error when file is present

### ISSUE THREAD

**Issue by hp2048** [pacific-2020/pacific#6]
I received following error when running PACIFIC.
```
Writing final output FASTA ./pacificoutput_testdata60.fasta.gz
Error in writing sequences - if -d/--tmpdir or -o/--outputdir flag supplied, check whether the supplied directory is available
```

If a file exists, then PACIFIC doesn't overwrite and generates this error. Perhaps a limited test is required for this.

**Comment by renzobalb** [comment]
Hi @hp2048, can you write the command used here? I tried using the test.fa.gz file and it seemed to overwrite the output with both the -o and -d flags. Perhaps there wasn't a tmpdir or outputdir available before running the program (if those flags were specified)?

**Comment by hp2048** [comment]
Hi @renzobalb : I didn't supply `-d` or `-o` flag. I used the following command:

```
python PACIFIC.py -i input.fasta.gz --model pacific.01.pacific_9mers_nonGPU.h5 --tokenizer tokenizer.01.pacific_9mers.pickle --label_maker label_maker.01.pacific_9mers.pickle --file_type fasta
```

**Comment by renzobalb** [comment]
Hmm interesting - PACIFIC should delete all tmp files regardless of whether it succeeds/fails. Tried the command above and it seems to be working. We can try replicating the error and find out what the issue is

**Comment by hp2048** [comment]
@renzobalb : For now, if tests results are good, then we can skip further testing. If problem arises again, we can look into it.
